### ISSUE TITLE
`captureOutput(_:didOutput:from:)` not be called.

### ISSUE THREAD

**Issue by longjianjiang** [WeTransfer/WeScan#33] opened 2018-07-06 06:50 UTC
When i run this demo project at ipad mini2 (11.4), it didn't call `AVCaptureVideoDataOutputSampleBufferDelegate` delegate method, so the screen is black, not capture any content.

And, i write the same function, it also have same problem when run on ipad mini2(11.4), here is my set `CaptureSession` code snippet.

```
  AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
    if (!device) return;
    self.captureDevice = device;
    
    _imageDetectionConfidence = 0.0;
    
    AVCaptureSession *session = [AVCaptureSession new];
    session.sessionPreset = AVCaptureSessionPresetPhoto;
    self.captureSession = session;
    
[session beginConfiguration];
   
    AVCaptureDeviceInput *input = [AVCaptureDeviceInput deviceInputWithDevice:device error:NULL];
    [session addInput:input];
    
    AVCaptureVideoDataOutput *dataOutput = [AVCaptureVideoDataOutput new];
    [dataOutput setAlwaysDiscardsLateVideoFrames:YES];
    [dataOutput setVideoSettings:@{ (NSString *)kCVPixelBufferPixelFormatTypeKey : @(kCVPixelFormatType_32BGRA)}];
    [dataOutput setSampleBufferDelegate:self queue:dispatch_get_main_queue()];
    [session addOutput:dataOutput];
    
    self.stillImageOutput = [[AVCaptureStillImageOutput alloc] init];
    [session addOutput:self.stillImageOutput];
    
    AVCaptureConnection *connection = [dataOutput.connections firstObject];
    [connection setVideoOrientation:AVCaptureVideoOrientationLandscapeLeft];
    
    if (device.isFlashAvailable) {
        [device lockForConfiguration:nil];
        [device setFlashMode:AVCaptureFlashModeOff];
        [device unlockForConfiguration];
    }
    
    if ([device isFocusModeSupported:AVCaptureFocusModeContinuousAutoFocus]) {
        [device lockForConfiguration:nil];
        [device setFocusMode:AVCaptureFocusModeContinuousAutoFocus];
        [device unlockForConfiguration];
    }
    
[session commitConfiguration];
```

I am so confused about this problem, want to get some help from your guys, thanks.

**Comment by longjianjiang** [comment] 2018-07-10 12:08
Today i use another iPad Mini2, this project and my project work normally; So i think it is a problem with that device.

**Comment by Boris-Em** [comment] 2018-07-16 07:29
Thanks for the update @longjianjiang! Closing as unable to reproduce.

**Closed by Boris-Em** 2018-07-16 07:29 UTC
Labels: bug
