### ISSUE TITLE
Rethink through the zoomed circle for squared corners

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeScan#62] opened 2018-09-17 07:48 UTC
> @nickseidel thanks for thinking with us here. I had the same discussion with @Boris-Em before, but he mentioned that we copied the exact same behaviour as the notes iOS app. Although we should handle Apple as a serious example, we might want to revisit this ourselves for better UX.

## What can we improve?
We might want to show the zoomed circle in an offset of the touch point, so it's visible in all scenarios. This does mean we step away from the Apple way of doing this, but the question is either way whether users are used to this Apple behaviour and whether we should just do the best for our users instead.

**Comment by justJS** [comment] 2018-09-17 07:50
I vote that we should detect the touch - if it's within a certain boundary of the actual corner, show the circle at an offset, otherwise, use the Apple behavior.

**Comment by justJS** [comment] 2018-10-01 08:45
Should we close this in favor of #61?

**Comment by Boris-Em** [comment] 2018-10-01 13:05
Good call @justJS. Closing as duplicate of #61.

**Closed by Boris-Em** 2018-10-01 13:05 UTC
Labels: enhancement, good first issue
