### ISSUE TITLE
Embedding with Objective-C.

### ISSUE THREAD

**Issue by johnmccambridge7** [WeTransfer/WeScan#175] opened 2019-06-25 00:11 UTC
I've found an issue with the setup involving objective-c with the swift library. Inside ImageScannerController.swift the init method is not being called when the scanner is called within Objective-C. 

public required init() {
        let scannerViewController = ScannerViewController()
        super.init(rootViewController: scannerViewController)
        navigationBar.tintColor = .black
        navigationBar.isTranslucent = false
        self.view.addSubview(blackFlashView)
        setupConstraints()
    }

Must be added inside to get this to work.

**Comment by AvdLee** [comment] 2019-07-22 08:53
@johnmccambridge7 feel free to open a PR for this!

**Comment by AvdLee** [comment] 2019-07-22 08:58
Closing as duplicate of https://github.com/WeTransfer/WeScan/issues/167

**Closed by AvdLee** 2019-07-22 08:58 UTC
Labels: bug, good first issue, help wanted
