### ISSUE TITLE
Bug when trying to run on Xcode 10, Swift 4.2

### ISSUE THREAD

**Issue by OkiRules** [WeTransfer/WeScan#48] opened 2018-08-01 11:39 UTC
When trying to run I get this error:

```
Showing All Messages
:-1: Multiple commands produce '/Users/oscargorog/Library/Developer/Xcode/DerivedData/Musiker-avnoagqbrsojuteinjszfpuhbrvr/Build/Products/Debug-iphonesimulator/WeScan/WeScan.framework/Info.plist':
1) Target 'WeScan' has copy command from '/Users/oscargorog/Desktop/Oscar's MacBook Pro/Coding/Musiker/Pods/WeScan/WeScan/Info.plist' to '/Users/oscargorog/Library/Developer/Xcode/DerivedData/Musiker-avnoagqbrsojuteinjszfpuhbrvr/Build/Products/Debug-iphonesimulator/WeScan/WeScan.framework/Info.plist'
2) Target 'WeScan' has process command with input '/Users/oscargorog/Desktop/Oscar's MacBook Pro/Coding/Musiker/Pods/Target Support Files/WeScan/Info.plist'
```

**Comment by justJS** [comment] 2018-08-01 11:45
When you brought in the WeScan folder you kept it's Info.plist - delete WeScan's info.plist otherwise Xcode will get confused about having 2.

**Comment by justJS** [comment] 2018-08-01 12:15
@Boris-Em I don't think this should be filed as a bug - it's an issue caused by Xcode getting confused when WeScan's folder is imported rather than using a framework manager.

**Comment by Boris-Em** [comment] 2018-08-01 13:42
@OkiRules Could you confirm that @justJS' suggestion fixes your problem?

**Comment by OkiRules** [comment] 2018-08-01 22:11
Yes it did. But I imported this by Cocoapods so this shouldn’t be a problem. 

Anyway thanks for your help.

**Comment by Boris-Em** [comment] 2018-08-02 07:24
Closing as fixed. Thanks @justJS!

**Closed by Boris-Em** 2018-08-02 07:24 UTC
Labels: help wanted
