### ISSUE TITLE
Error: Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by aronnelson** [WeTransfer/WeScan#354] opened 2023-06-06 20:30 UTC
Xcode 15.

Getting Error: Stored properties cannot be marked unavailable with '@available'

@available(*, unavailable, renamed: "originalScan")
    public var originalImage: UIImage?

    @available(*, unavailable, renamed: "croppedScan")
    public var scannedImage: UIImage?

    @available(*, unavailable, renamed: "enhancedScan")
    public var enhancedImage: UIImage?

    @available(*, unavailable, renamed: "doesUserPreferEnhancedScan")
    public var doesUserPreferEnhancedImage = false

**Comment by BasThomas** [comment] 2023-06-21 13:44
Thanks @aronnelson! I'm to close this as a duplicate of #359 for now, but thanks for reporting!

**Closed by BasThomas** 2023-06-21 13:44 UTC
